version: '3.9'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://modern-myrtice-mgdev-52e185a8.koyeb.app/api}
    container_name: prostock-frontend
    ports:
      - "8089:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s